### ISSUE TITLE
Node v6.0.0

### ISSUE THREAD

**Issue by tianp** [nodesource/upgrade-ready#13]
Is there anything I can help to support checking for Node v6.0.0?

Tried:

```
upgrade-ready 6.0.0
```

Result:

```
Version does not exist in Node.js or io.js - v6.0.0
```

**Comment by julianduque** [comment]
Hello @tianp, I just installed v6.0.0 on the server, can you try again and let me know if it worked? Thanks!

**Comment by tianp** [comment]
Cool, it worked now! Thanks @julianduque 👍
