### ISSUE TITLE
How to test private registry dependencies?

### ISSUE THREAD

**Issue by jonathansamines** [nodesource/upgrade-ready#3]
There is a way to run this test against a private server? or how to test dependencies published on a private npm registry?

**Comment by julianduque** [comment]
@jonathansamines currently it works only with public dependencies and the public npm registry, I'll figure out how to add support for private instances

**Comment by michaelerobertsjr** [comment]
@julianduque +1 we have a private registry and it definitely would be helpful to be able to use this tool.

**Comment by michaelerobertsjr** [comment]
Also, looks like it is inspecting package.json.... what about for those of us that use npm-shrinkwrap.json?

**Comment by marcellodesales** [comment]
Hi @julianduque, +1 for private registries! It broke after the attempt to `npm install` our private libraries... Could you provide this as a CLI or a Docker container?

**Comment by marcellodesales** [comment]
@julianduque, Is there a way to provide this tool for paid NodeSource customers? As a platform, this is a very important tool to verify compatibility of applications that want to onboard in our PaaS.

**Comment by julianduque** [comment]
@marcellodesales currently it would be possible to do if:
- Private registry has access from outside (it's visible from our servers)
- User share private registry url and auth credentials with our server (we don't store that information though)

**Comment by marcellodesales** [comment]
@julianduque That's definitely NOT an option for us... Our server is behind a proxy and there's NO way we can provide this... 

Why don't you guys provide a Docker container with your stuff obfuscated/encrypted etc? That would make people's lives easier...

**Comment by julianduque** [comment]
@marcellodesales we are working on a workaround for this that will fit your needs :), will let you know when ready.

**Comment by marcellodesales** [comment]
@julianduque Cool... I heard that you would have it this week... Any good news yet?

**Comment by julianduque** [comment]
@marcellodesales yes! Doing some testing and docs and you'll have access to it ;)

**Comment by marcellodesales** [comment]
@julianduque  Can't wait!

**Comment by julianduque** [comment]
Option is already available for [N|Support](https://nodesource.com/services/nsupport) customers
