### ISSUE TITLE
Can not understand the output for a failed module

### ISSUE THREAD

**Issue by ali-bugdayci** [nodesource/upgrade-ready#5]
The output for the failed grunt-contrib-watch is not clear:
http://upgrade-ready.nodesource.com/summary/0a8433f0-936e-11e5-ab3c-3bac1dbd8d71

What might be causing the module not to be node 4 compliant.

Linked issue under grunt-watch:
https://github.com/gruntjs/grunt-contrib-watch/issues/475

**Comment by cronopio** [comment]
Hi @ali-bugdayci can you try to trigger the report again, seems the installation have a weird fail. Let us know if after a try you get the same result.

Thanks!

**Comment by ali-bugdayci** [comment]
Hi,

Thanks for the fast response. Actually I got the same error on my different project so I tested it out in a blank project.

I tested it out again and got the same error:
 http://upgrade-ready.nodesource.com/summary/689394c0-980c-11e5-ab3c-3bac1dbd8d71

You can access the sample project from:
https://github.com/ali-bugdayci/upgrade-ready-test.git

**Comment by cronopio** [comment]
Thank you for taking the time. We're investigating

**Comment by cronopio** [comment]
@ali-bugdayci Sorry about this issue, please try again generating a new report. I did some cleanup on cache and database. Let us know if you get same result.

**Comment by ali-bugdayci** [comment]
Great. Thanks for the effort
