### ISSUE TITLE
Report shows 2 packages failed the test, but unclear why

### ISSUE THREAD

**Issue by piotrd** [nodesource/upgrade-ready#6]
Hi,

My report shows that 2 packages (`require-dir` and `vinyl-source-stream`) have failed readiness test against node v.4.2.3: http://upgrade-ready.nodesource.com/summary/41973b70-9cfc-11e5-9d3e-9f93a8a5e566. The errors I got are the same for both packages:

```
npm ERR! Linux 3.13.0-57-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "require-dir@0.3.0" "-d" "--nodedir=\"/root/.nvm/versions/node/v4.2.3\""
npm ERR! node v4.2.3
npm ERR! npm  v2.14.14
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package undefined does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer karma-browserify@4.4.2 wants undefined@>=0.10
npm ERR! peerinvalid Peer karma-phantomjs-launcher@0.2.1 wants undefined@>=0.9

npm ERR! Please include the following file with any support request:
npm ERR!     /var/upgrade-ready/4d5cae60-9cc8-11e5-9d3e-9f93a8a5e566/npm-debug.log
```

However, packages mentioned in the error above are not dependencies of either of packages that failed the readiness test. I did repeat the test after a few hours and got the same result, so I think it's not a matter of test infrastructure being overloaded. Or is it? Any input would be appreciated.

**Comment by julianduque** [comment]
@piotrd `upgrade-ready` uses npm behind the curtains to check for node v4 readiness, it seems this package was having issues with their peerDependencies (to be deprecated in npm@3)

**Comment by piotrd** [comment]
OK, thanks.
